# migrations/versions/71d0518a6feb_add_otp_column_to_user_table.py (example)
"""Add otp column to user table

Revision ID: 71d0518a6feb
Revises: 
Create Date: 2024-12-21 02:08:20.123456

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '71d0518a6feb'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp')
    # ### end Alembic commands ###